In [2]:
import pandas as pd
import polars as pl
from pathlib import Path

In [3]:
raw_data_dir = Path.cwd().parent / 'data_gather' / 'raw_data'
filtered_data_dir = Path.cwd().parent / 'data_gather' / 'filtered_data'

In [ ]:
trades = pl.scan_csv(raw_data_dir / 'coinbase_trades.csv').collect()
options = pl.scan_csv(raw_data_dir / 'deribit_option_vols.csv').collect()
kalshi = pl.scan_csv(raw_data_dir / 'kalshi_markets.csv').collect()
polymarket = pl.scan_csv(raw_data_dir / 'polymarket_markets.csv').collect()

In [20]:
filterer = filter_data(['BTC', 'ETH'])
df = filterer.clean_trades(trades)

In [ ]:
dfz = df.with_columns(
    pl.col("curr_time")
    .str.to_datetime(format="%Y-%m-%d %H:%M:%S%.f%#z", strict=False)
    .alias("curr_time"))

dfz.head()

shape: (5, 8)
┌─────┬────────────────┬────────────┬────────────────┬──────────┬───────────┬──────┬───────────────┐
│ id  ┆ curr_time      ┆ product_id ┆ trade_time     ┆ price    ┆ size      ┆ side ┆ curr_time_rea │
│ --- ┆ ---            ┆ ---        ┆ ---            ┆ ---      ┆ ---       ┆ ---  ┆ dable         │
│ u32 ┆ datetime[μs,   ┆ str        ┆ str            ┆ f64      ┆ f64       ┆ str  ┆ ---           │
│     ┆ UTC]           ┆            ┆                ┆          ┆           ┆      ┆ str           │
╞═════╪════════════════╪════════════╪════════════════╪══════════╪═══════════╪══════╪═══════════════╡
│ 0   ┆ 2026-03-21 10: ┆ BTC-USD    ┆ 2026-03-21 10: ┆ 70565.43 ┆ 0.000084  ┆ sell ┆ 2026-03-21    │
│     ┆ 47:31.458355   ┆            ┆ 47:31.433808+0 ┆          ┆           ┆      ┆ 06:47:31      │
│     ┆ UTC            ┆            ┆ 0:…            ┆          ┆           ┆      ┆               │
│ 1   ┆ 2026-03-21 10: ┆ BTC-USD    ┆ 2026-03-21 10: ┆ 70565.43 ┆ 4.4000e-7 ┆ sell ┆ 2026-03-21    │
│     ┆ 47:31.573966   ┆            ┆ 47:31.554989+0 ┆          ┆           ┆      ┆ 06:47:31      │
│     ┆ UTC            ┆            ┆ 0:…            ┆          ┆           ┆      ┆               │
│ 2   ┆ 2026-03-21 10: ┆ ETH-USD    ┆ 2026-03-21 10: ┆ 2153.74  ┆ 0.000556  ┆ sell ┆ 2026-03-21    │
│     ┆ 47:31.705201   ┆            ┆ 47:31.697621+0 ┆          ┆           ┆      ┆ 06:47:31      │
│     ┆ UTC            ┆            ┆ 0:…            ┆          ┆           ┆      ┆               │
│ 3   ┆ 2026-03-21 10: ┆ ETH-USD    ┆ 2026-03-21 10: ┆ 2153.73  ┆ 0.000596  ┆ buy  ┆ 2026-03-21    │
│     ┆ 47:32.041475   ┆            ┆ 47:32.029096+0 ┆          ┆           ┆      ┆ 06:47:32      │
│     ┆ UTC            ┆            ┆ 0:…            ┆          ┆           ┆      ┆               │
│ 4   ┆ 2026-03-21 10: ┆ ETH-USD    ┆ 2026-03-21 10: ┆ 2153.73  ┆ 0.1502702 ┆ buy  ┆ 2026-03-21    │
│     ┆ 47:32.041505   ┆            ┆ 47:32.029096+0 ┆          ┆           ┆      ┆ 06:47:32      │
│     ┆ UTC            ┆            ┆ 0:…            ┆          ┆           ┆      ┆               │
└─────┴────────────────┴────────────┴────────────────┴──────────┴───────────┴──────┴───────────────┘

In [34]:
class filter_data(): 
    def __init__(self
                 , trades: pl.DataFrame
                 , options: pl.DataFrame
                 , kalshi: pl.DataFrame
                 , polymarket: pl.DataFrame):
        
        self.trades = trades
        self.options = options
        self.kalshi = kalshi
        self.polymarket = polymarket
    
    def clean_trades(self, coins: list) -> pl.DataFrame:
        coin_trades = self.trades.filter(pl.col('product_id').is_in([f'{coin}-USD' for coin in coins]))
        coin_trades = coin_trades.unique(subset=['trade_id'])
        coin_trades = coin_trades.sort('trade_time', descending=False)
        coin_trades = coin_trades.drop('id').with_row_index('id')
        coin_trades = coin_trades.select('id', 'curr_time', 'product_id', 'trade_time', 'price', 'size', 'side')
        return coin_trades
    
    def clean_options(self, coins: list) -> pl.DataFrame: 
        coin_options = self.options.filter(pl.col('currency').is_in([f'{coin}' for coin in coins]))
        coin_options = coin_options.sort('curr_time', descending=False)
        coin_options = coin_options.drop('id').with_row_index('id')
        coin_options = coin_options.select('id', 'curr_time', 'instrument_name', 'expiry_datetime', 'strike', 
                                           'option_type', 'underlying_price', 'delta', 'mark_iv', 'mark_price', 
                                           'open_interest', 'volume')
        return coin_options
    
    def clean_kalshi(self, coins: list) -> pl.DataFrame: 
        coin_kalshi = self.kalshi.filter(pl.col('coin').is_in([f'{coin}' for coin in coins]))
        coin_kalshi = coin_kalshi.sort('curr_time', descending=False)
        coin_kalshi = coin_kalshi.drop('id').with_row_index('id')
        coin_kalshi = coin_kalshi.select('id', 'curr_time', 'coin', 'open_time', 'close_time', 
                                         'last_price_dollars' , 'no_ask_dollars', 'no_bid_dollars', 
                                         'yes_ask_dollars', 'yes_bid_dollars', 'floor_strike', 'volume_24h_fp')
        return coin_kalshi
    
    def clean_polymarket(self, coins: list) -> pl.DataFrame:
        coin_polymarket = self.polymarket.filter(pl.col('coin').is_in([f'{coin}' for coin in coins]))
        coin_polymarket = coin_polymarket.sort('curr_time', descending=False)
        coin_polymarket = coin_polymarket.drop('id').with_row_index('id')
        coin_polymarket = coin_polymarket.select('id', 'curr_time', 'coin', 'interval_start_unix', 'end_date', 'strike_price',
                                                 'liquidity', 'volume', 'yes_implied_price', 'no_implied_price', 'yes_buy_price',
                                                 'yes_sell_price', 'no_buy_price', 'no_sell_price')
        return coin_polymarket

In [37]:
FILTERER = filter_data(trades=trades, options=options, kalshi=kalshi, polymarket=polymarket)

In [40]:
btc_trades = FILTERER.clean_trades(['BTC']).write_csv(filtered_data_dir / 'btc_trades.csv')
btc_eth_options = FILTERER.clean_options(['BTC', 'ETH']).write_csv(filtered_data_dir / 'btc_eth_options.csv')
all_coins_kalshi = FILTERER.clean_kalshi(['BTC', 'ETH', 'XRP', 'SOL']).write_csv(filtered_data_dir / 'all_kalshi.csv')
all_coins_polymarket = FILTERER.clean_polymarket(['BTC', 'ETH', 'XRP', 'SOL']).write_csv(filtered_data_dir / 'all_polymarket.csv')

In [ ]:
clean_options = options.filter(pl.col('option_type') == 'call').drop('option_type').with_row_index('id')

In [30]:
btc_trades = btc_trades.with_columns(
    ((pl.col("price") * pl.col("size")) * pl.when(pl.col("side") == "buy").then(1).otherwise(-1)).alias("weighted")
)
btc_trades['weighted'].sum()

-42187385.281208575

In [ ]:
options.head()

shape: (5, 15)
┌─────────┬─────────────┬──────────┬────────────┬───┬───────────┬────────────┬────────────┬────────┐
│ id      ┆ curr_time   ┆ currency ┆ instrument ┆ … ┆ ask_price ┆ mark_price ┆ open_inter ┆ volume │
│ ---     ┆ ---         ┆ ---      ┆ _name      ┆   ┆ ---       ┆ ---        ┆ est        ┆ ---    │
│ i64     ┆ str         ┆ str      ┆ ---        ┆   ┆ str       ┆ f64        ┆ ---        ┆ f64    │
│         ┆             ┆          ┆ str        ┆   ┆           ┆            ┆ f64        ┆        │
╞═════════╪═════════════╪══════════╪════════════╪═══╪═══════════╪════════════╪════════════╪════════╡
│ 1120902 ┆ 2026-03-21  ┆ ETH      ┆ ETH-22MAR2 ┆ … ┆ null      ┆ 0.0015     ┆ 7364.0     ┆ 6292.0 │
│         ┆ 16:47:26.15 ┆          ┆ 6-2125-P   ┆   ┆           ┆            ┆            ┆        │
│         ┆ 5308+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120903 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.0013     ┆ 84.9       ┆ 82.9   │
│         ┆ 16:47:31.15 ┆          ┆ 6-71000-C  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120904 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.0035     ┆ 222.4      ┆ 134.8  │
│         ┆ 16:47:31.15 ┆          ┆ 6-70500-C  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120905 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.002      ┆ 561.6      ┆ 189.5  │
│         ┆ 16:47:31.15 ┆          ┆ 6-70000-P  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120906 ┆ 2026-03-21  ┆ ETH      ┆ ETH-22MAR2 ┆ … ┆ null      ┆ 0.0015     ┆ 1176.0     ┆ 890.0  │
│         ┆ 16:47:31.15 ┆          ┆ 6-2175-C   ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
└─────────┴─────────────┴──────────┴────────────┴───┴───────────┴────────────┴────────────┴────────┘

In [ ]:
kalshi.head()

shape: (5, 17)
┌─────────┬─────────────┬──────┬─────────────┬───┬────────────┬─────────────┬────────┬─────────────┐
│ id      ┆ curr_time   ┆ coin ┆ open_time   ┆ … ┆ cap_strike ┆ strike_type ┆ volume ┆ volume_24h_ │
│ ---     ┆ ---         ┆ ---  ┆ ---         ┆   ┆ ---        ┆ ---         ┆ ---    ┆ fp          │
│ i64     ┆ str         ┆ str  ┆ str         ┆   ┆ str        ┆ str         ┆ str    ┆ ---         │
│         ┆             ┆      ┆             ┆   ┆            ┆             ┆        ┆ f64         │
╞═════════╪═════════════╪══════╪═════════════╪═══╪════════════╪═════════════╪════════╪═════════════╡
│ 4200710 ┆ 2026-03-23  ┆ XRP  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:15.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 1426+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200711 ┆ 2026-03-23  ┆ SOL  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:15.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 1426+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200712 ┆ 2026-03-23  ┆ BTC  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200713 ┆ 2026-03-23  ┆ ETH  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200714 ┆ 2026-03-23  ┆ XRP  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
└─────────┴─────────────┴──────┴─────────────┴───┴────────────┴─────────────┴────────┴─────────────┘

In [ ]:
polymarket.head()

shape: (5, 18)
┌─────┬─────────────┬──────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ id  ┆ curr_time   ┆ coin ┆ time_horizo ┆ … ┆ yes_buy_pri ┆ yes_sell_pr ┆ no_buy_pri ┆ no_sell_pr │
│ --- ┆ ---         ┆ ---  ┆ n_minutes   ┆   ┆ ce          ┆ ice         ┆ ce         ┆ ice        │
│ i64 ┆ str         ┆ str  ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│     ┆             ┆      ┆ i64         ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════╪═════════════╪══════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0   ┆ 2026-03-28  ┆ ETH  ┆ 15          ┆ … ┆ 0.47        ┆ 0.48        ┆ 0.52       ┆ 0.53       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 1   ┆ 2026-03-28  ┆ XRP  ┆ 15          ┆ … ┆ 0.45        ┆ 0.46        ┆ 0.54       ┆ 0.55       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 2   ┆ 2026-03-28  ┆ SOL  ┆ 15          ┆ … ┆ 0.49        ┆ 0.5         ┆ 0.5        ┆ 0.51       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 3   ┆ 2026-03-28  ┆ BTC  ┆ 15          ┆ … ┆ 0.54        ┆ 0.55        ┆ 0.45       ┆ 0.46       │
│     ┆ 18:00:43.73 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5854+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 4   ┆ 2026-03-28  ┆ ETH  ┆ 15          ┆ … ┆ 0.47        ┆ 0.48        ┆ 0.52       ┆ 0.53       │
│     ┆ 18:00:43.73 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5854+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
└─────┴─────────────┴──────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘