In [6]:
import pandas as pd
import polars as pl
from pathlib import Path

In [7]:
raw_data_dir = Path.cwd().parent / 'data_gather' / 'raw_data'
filtered_data_dir = Path.cwd().parent / 'data_gather' / 'filtered_data'

In [9]:
trades = pl.scan_csv(raw_data_dir / 'coinbase_trades.csv').collect()
options = pl.scan_csv(raw_data_dir / 'deribit_option_vols.csv').collect()
kalshi = pl.scan_csv(raw_data_dir / 'kalshi_markets.csv').collect()
polymarket = pl.scan_csv(raw_data_dir / 'polymarket_markets.csv').collect()

In [ ]:
dfz = df.with_columns(
    pl.col("curr_time")
    .str.to_datetime(format="%Y-%m-%d %H:%M:%S%.f%#z", strict=False)
    .alias("curr_time"))

dfz.head()

NameError: name 'df' is not defined

In [10]:
class filter_data(): 
    def __init__(self
                 , trades: pl.DataFrame
                 , options: pl.DataFrame
                 , kalshi: pl.DataFrame
                 , polymarket: pl.DataFrame):
        
        self.trades = trades
        self.options = options
        self.kalshi = kalshi
        self.polymarket = polymarket
    
    def clean_trades(self, coins: list) -> pl.DataFrame:
        coin_trades = self.trades.filter(pl.col('product_id').is_in([f'{coin}-USD' for coin in coins]))
        coin_trades = coin_trades.unique(subset=['trade_id'])
        coin_trades = coin_trades.sort('trade_time', descending=False)
        coin_trades = coin_trades.drop('id').with_row_index('id')
        coin_trades = coin_trades.select('id', 'curr_time', 'product_id', 'trade_time', 'price', 'size', 'side')
        return coin_trades
    
    def clean_options(self, coins: list) -> pl.DataFrame: 
        coin_options = self.options.filter(pl.col('currency').is_in([f'{coin}' for coin in coins]))
        coin_options = coin_options.sort('curr_time', descending=False)
        coin_options = coin_options.drop('id').with_row_index('id')
        coin_options = coin_options.select('id', 'curr_time', 'instrument_name', 'expiry_datetime', 'strike', 
                                           'option_type', 'underlying_price', 'delta', 'mark_iv', 'mark_price', 
                                           'open_interest', 'volume')
        return coin_options
    
    def clean_kalshi(self, coins: list) -> pl.DataFrame: 
        coin_kalshi = self.kalshi.filter(pl.col('coin').is_in([f'{coin}' for coin in coins]))
        coin_kalshi = coin_kalshi.sort('curr_time', descending=False)
        coin_kalshi = coin_kalshi.drop('id').with_row_index('id')
        coin_kalshi = coin_kalshi.select('id', 'curr_time', 'coin', 'open_time', 'close_time', 
                                         'last_price_dollars' , 'no_ask_dollars', 'no_bid_dollars', 
                                         'yes_ask_dollars', 'yes_bid_dollars', 'floor_strike', 'volume_24h_fp')
        return coin_kalshi
    
    def clean_polymarket(self, coins: list) -> pl.DataFrame:
        coin_polymarket = self.polymarket.filter(pl.col('coin').is_in([f'{coin}' for coin in coins]))
        coin_polymarket = coin_polymarket.sort('curr_time', descending=False)
        coin_polymarket = coin_polymarket.drop('id').with_row_index('id')
        coin_polymarket = coin_polymarket.select('id', 'curr_time', 'coin', 'interval_start_unix', 'end_date', 'strike_price',
                                                 'liquidity', 'volume', 'yes_implied_price', 'no_implied_price', 'yes_buy_price',
                                                 'yes_sell_price', 'no_buy_price', 'no_sell_price')
        return coin_polymarket

In [17]:
FILTERER = filter_data(trades=trades, options=options, kalshi=kalshi, polymarket=polymarket)

In [96]:
btc_trades = FILTERER.clean_trades(['BTC'])
btc_eth_options = FILTERER.clean_options(['BTC', 'ETH'])
all_coins_kalshi = FILTERER.clean_kalshi(['BTC', 'ETH', 'XRP', 'SOL'])
all_coins_polymarket = FILTERER.clean_polymarket(['BTC', 'ETH', 'XRP', 'SOL'])

In [97]:
def _to_datetime(table: pl.DataFrame, cols: list) -> pl.DataFrame:
    for col in cols: 
        table = table.with_columns(
            pl.col(col)
            .str.to_datetime(format="%Y-%m-%d %H:%M:%S%.f%#z", strict=False)
            .alias(col)
        )
    return table

In [ ]:
btc_trades = _to_datetime(btc_trades, ['curr_time', 'trade_time'])
btc_eth_options = _to_datetime(btc_eth_options, ['curr_time', 'expiry_datetime'])
all_coins_kalshi = _to_datetime(all_coins_kalshi, ['curr_time', 'open_time', 'close_time'])
all_coins_polymarket = _to_datetime(all_coins_polymarket, ['curr_time', 'end_date'])

In [ ]:
first_event_time, last_event_time = all_coins_kalshi.select(pl.col('open_time').min(), pl.col('close_time').max()).row(0)

all_coins_kalshi = all_coins_kalshi.filter(~((pl.col("open_time") == first_event_time) | (pl.col("close_time") == last_event_time)))
all_coins_kalshi.head()
all_coins_kalshi.group_by(('open_time')).agg(pl.len()).sort('open_time')

In [ ]:

df = df.with_columns(
    pl.col("curr_time").shift(1).over("coin").alias("prev_time")
).with_columns(
    (pl.col("curr_time") - pl.col("prev_time"))
    .dt.total_seconds()
    .alias("time_diff_seconds")
)

df = df.filter(pl.col("time_diff_seconds").is_between(0.9, 1.1))
df['time_diff_seconds'].value_counts()



df

In [ ]:
def build_coin_df(df: pl.DataFrame, coin: str) -> pl.DataFrame:
    col_identifiers = ["open_time", "close_time"]

    df = (
        df
        .filter(pl.col("coin") == coin)
        .sort(col_identifiers + ["curr_time"])
        .with_columns(
            pl.col("last_price_dollars")
            .shift(-1)
            .over(col_identifiers)
            .alias("next_price_dollars_lead1")
        )
        .filter(pl.col("time_to_close") > -0.01)
    )

    rename_map = {
        col: f"{coin}_{col}"
        for col in df.columns
    }

    df = df.rename(rename_map)

    return df

df = df.with_columns((pl.col('close_time') - pl.col('curr_time')).dt.total_seconds().alias('time_to_close'))



coin_dfs = [build_coin_df(df, coin) for coin in ["BTC", "ETH", "XRP", "SOL"]]

combined = coin_dfs[0]
for next_df in coin_dfs[1:]:
    combined = combined.join(
        next_df,
        on=["open_time", "close_time"],
        how="inner",
    )

combined = combined.filter(
    pl.col("BTC_next_price_dollars_lead1").is_not_null()
)

drop_cols = [col for col in ["BTC_coin", "ETH_coin", "XRP_coin", "SOL_coin"] if col in combined.columns]
combined = combined.drop(drop_cols)

outcome_map = (
    combined
    .sort("BTC_curr_time")
    .group_by("BTC_open_time")
    .agg(
        pl.col("BTC_last_price_dollars").last().alias("last_btc_price")
    )
    .with_columns(
        (pl.col("last_btc_price") > 0.5).cast(pl.Int8).alias("outcome")
    )
    .select(["BTC_open_time", "outcome"])
)

combined = combined.join(outcome_map, on="BTC_open_time", how="left")
combined.head()

In [ ]:
btc_trades = _to_datetime(btc_trades, ['curr_time', 'trade_time'])

joined = btc_trades.join_asof(df, left_on= 'trade_time', right_on='curr_time', strategy='forward')

In [87]:
joined = joined.filter((pl.col('trade_time') >= pl.col('prev_time')) & (pl.col('trade_time') <= pl.col('curr_time')))
joined

shape: (8_425_362, 21)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id      ┆ curr_time  ┆ product_i ┆ trade_tim ┆ … ┆ floor_str ┆ volume_24 ┆ prev_time ┆ time_diff │
│ ---     ┆ ---        ┆ d         ┆ e         ┆   ┆ ike       ┆ h_fp      ┆ ---       ┆ _seconds  │
│ i64     ┆ datetime[μ ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ datetime[ ┆ ---       │
│         ┆ s, UTC]    ┆ str       ┆ datetime[ ┆   ┆ f64       ┆ f64       ┆ μs, UTC]  ┆ i64       │
│         ┆            ┆           ┆ μs, UTC]  ┆   ┆           ┆           ┆           ┆           │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1941    ┆ 2026-03-21 ┆ BTC-USD   ┆ 2026-03-2 ┆ … ┆ 2153.8    ┆ 0.0       ┆ 2026-03-2 ┆ 1         │
│         ┆ 11:00:10.8 ┆           ┆ 1 11:00:1 ┆   ┆           ┆           ┆ 1 11:00:1 ┆           │
│         ┆ 46647 UTC  ┆           ┆ 0.757698  ┆   ┆           ┆           ┆ 0.404408  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 1942    ┆ 2026-03-21 ┆ BTC-USD   ┆ 2026-03-2 ┆ … ┆ 2153.8    ┆ 0.0       ┆ 2026-03-2 ┆ 1         │
│         ┆ 11:00:11.0 ┆           ┆ 1 11:00:1 ┆   ┆           ┆           ┆ 1 11:00:1 ┆           │
│         ┆ 61872 UTC  ┆           ┆ 1.053426  ┆   ┆           ┆           ┆ 0.404408  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 1943    ┆ 2026-03-21 ┆ BTC-USD   ┆ 2026-03-2 ┆ … ┆ 2153.8    ┆ 0.0       ┆ 2026-03-2 ┆ 1         │
│         ┆ 11:00:11.3 ┆           ┆ 1 11:00:1 ┆   ┆           ┆           ┆ 1 11:00:1 ┆           │
│         ┆ 45054 UTC  ┆           ┆ 1.341167  ┆   ┆           ┆           ┆ 0.404408  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 1944    ┆ 2026-03-21 ┆ BTC-USD   ┆ 2026-03-2 ┆ … ┆ 2153.8    ┆ 0.0       ┆ 2026-03-2 ┆ 1         │
│         ┆ 11:00:11.8 ┆           ┆ 1 11:00:1 ┆   ┆           ┆           ┆ 1 11:00:1 ┆           │
│         ┆ 83842 UTC  ┆           ┆ 1.878472  ┆   ┆           ┆           ┆ 1.405555  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 1945    ┆ 2026-03-21 ┆ BTC-USD   ┆ 2026-03-2 ┆ … ┆ 2153.8    ┆ 0.0       ┆ 2026-03-2 ┆ 1         │
│         ┆ 11:00:11.8 ┆           ┆ 1 11:00:1 ┆   ┆           ┆           ┆ 1 11:00:1 ┆           │
│         ┆ 83768 UTC  ┆           ┆ 1.878472  ┆   ┆           ┆           ┆ 1.405555  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ …       ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 8436688 ┆ 2026-04-03 ┆ BTC-USD   ┆ 2026-04-0 ┆ … ┆ 66783.369 ┆ 57760.08  ┆ 2026-04-0 ┆ 1         │
│         ┆ 01:30:37.5 ┆           ┆ 3 01:30:3 ┆   ┆ 999       ┆           ┆ 3 01:30:3 ┆           │
│         ┆ 72996 UTC  ┆           ┆ 7.515937  ┆   ┆           ┆           ┆ 7.164514  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 8436689 ┆ 2026-04-03 ┆ BTC-USD   ┆ 2026-04-0 ┆ … ┆ 66783.369 ┆ 57760.08  ┆ 2026-04-0 ┆ 1         │
│         ┆ 01:30:37.5 ┆           ┆ 3 01:30:3 ┆   ┆ 999       ┆           ┆ 3 01:30:3 ┆           │
│         ┆ 73036 UTC  ┆           ┆ 7.515937  ┆   ┆           ┆           ┆ 7.164514  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 8436690 ┆ 2026-04-03 ┆ BTC-USD   ┆ 2026-04-0 ┆ … ┆ 66783.369 ┆ 57760.08  ┆ 2026-04-0 ┆ 1         │
│         ┆ 01:30:37.9 ┆           ┆ 3 01:30:3 ┆   ┆ 999       ┆           ┆ 3 01:30:3 ┆           │
│         ┆ 41328 UTC  ┆           ┆ 7.936154  ┆   ┆           ┆           ┆ 7.164514  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 8436691 ┆ 2026-04-03 ┆ BTC-USD   ┆ 2026-04-0 ┆ … ┆ 66783.369 ┆ 57760.08  ┆ 2026-04-0 ┆ 1         │
│         ┆ 01:30:39.1 ┆           ┆ 3 01:30:3 ┆   ┆ 999       ┆           ┆ 3 01:30:3 ┆           │
│         ┆ 70498 UTC  ┆           ┆ 9.164397  ┆   ┆           ┆           ┆ 8.165010  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
│ 8436692 ┆ 2026-04-03 ┆ BTC-USD   ┆ 2026-04-0 ┆ … ┆ 66783.369 ┆ 57760.08  ┆ 2026-04-0 ┆ 1         │
│         ┆ 01:30:39.7 ┆           ┆ 3 01:30:3 ┆   ┆ 999       ┆           ┆ 3 01:30:3 ┆           │
│         ┆ 89489 UTC  ┆           ┆ 9.784228  ┆   ┆           ┆           ┆ 9.165727  ┆           │
│         ┆            ┆           ┆ UTC       ┆   ┆           ┆           ┆ UTC       ┆           │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [ ]:
btc_trades = btc_trades.with_columns(
    ((pl.col("price") * pl.col("size")) * pl.when(pl.col("side") == "buy").then(1).otherwise(-1)).alias("weighted")
)
btc_trades['weighted'].sum()

In [ ]:
clean_options = options.filter(pl.col('option_type') == 'call').drop('option_type').with_row_index('id')

In [ ]:
options.head()

shape: (5, 15)
┌─────────┬─────────────┬──────────┬────────────┬───┬───────────┬────────────┬────────────┬────────┐
│ id      ┆ curr_time   ┆ currency ┆ instrument ┆ … ┆ ask_price ┆ mark_price ┆ open_inter ┆ volume │
│ ---     ┆ ---         ┆ ---      ┆ _name      ┆   ┆ ---       ┆ ---        ┆ est        ┆ ---    │
│ i64     ┆ str         ┆ str      ┆ ---        ┆   ┆ str       ┆ f64        ┆ ---        ┆ f64    │
│         ┆             ┆          ┆ str        ┆   ┆           ┆            ┆ f64        ┆        │
╞═════════╪═════════════╪══════════╪════════════╪═══╪═══════════╪════════════╪════════════╪════════╡
│ 1120902 ┆ 2026-03-21  ┆ ETH      ┆ ETH-22MAR2 ┆ … ┆ null      ┆ 0.0015     ┆ 7364.0     ┆ 6292.0 │
│         ┆ 16:47:26.15 ┆          ┆ 6-2125-P   ┆   ┆           ┆            ┆            ┆        │
│         ┆ 5308+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120903 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.0013     ┆ 84.9       ┆ 82.9   │
│         ┆ 16:47:31.15 ┆          ┆ 6-71000-C  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120904 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.0035     ┆ 222.4      ┆ 134.8  │
│         ┆ 16:47:31.15 ┆          ┆ 6-70500-C  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120905 ┆ 2026-03-21  ┆ BTC      ┆ BTC-22MAR2 ┆ … ┆ null      ┆ 0.002      ┆ 561.6      ┆ 189.5  │
│         ┆ 16:47:31.15 ┆          ┆ 6-70000-P  ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
│ 1120906 ┆ 2026-03-21  ┆ ETH      ┆ ETH-22MAR2 ┆ … ┆ null      ┆ 0.0015     ┆ 1176.0     ┆ 890.0  │
│         ┆ 16:47:31.15 ┆          ┆ 6-2175-C   ┆   ┆           ┆            ┆            ┆        │
│         ┆ 6183+00:…   ┆          ┆            ┆   ┆           ┆            ┆            ┆        │
└─────────┴─────────────┴──────────┴────────────┴───┴───────────┴────────────┴────────────┴────────┘

In [ ]:
kalshi.head()

shape: (5, 17)
┌─────────┬─────────────┬──────┬─────────────┬───┬────────────┬─────────────┬────────┬─────────────┐
│ id      ┆ curr_time   ┆ coin ┆ open_time   ┆ … ┆ cap_strike ┆ strike_type ┆ volume ┆ volume_24h_ │
│ ---     ┆ ---         ┆ ---  ┆ ---         ┆   ┆ ---        ┆ ---         ┆ ---    ┆ fp          │
│ i64     ┆ str         ┆ str  ┆ str         ┆   ┆ str        ┆ str         ┆ str    ┆ ---         │
│         ┆             ┆      ┆             ┆   ┆            ┆             ┆        ┆ f64         │
╞═════════╪═════════════╪══════╪═════════════╪═══╪════════════╪═════════════╪════════╪═════════════╡
│ 4200710 ┆ 2026-03-23  ┆ XRP  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:15.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 1426+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200711 ┆ 2026-03-23  ┆ SOL  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:15.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 1426+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200712 ┆ 2026-03-23  ┆ BTC  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200713 ┆ 2026-03-23  ┆ ETH  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
│ 4200714 ┆ 2026-03-23  ┆ XRP  ┆ 2026-03-23  ┆ … ┆ null       ┆ greater_or_ ┆ null   ┆ 0.0         │
│         ┆ 06:21:16.23 ┆      ┆ 06:15:00+00 ┆   ┆            ┆ equal       ┆        ┆             │
│         ┆ 2547+00:…   ┆      ┆ :00         ┆   ┆            ┆             ┆        ┆             │
└─────────┴─────────────┴──────┴─────────────┴───┴────────────┴─────────────┴────────┴─────────────┘

In [ ]:
polymarket.head()

shape: (5, 18)
┌─────┬─────────────┬──────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ id  ┆ curr_time   ┆ coin ┆ time_horizo ┆ … ┆ yes_buy_pri ┆ yes_sell_pr ┆ no_buy_pri ┆ no_sell_pr │
│ --- ┆ ---         ┆ ---  ┆ n_minutes   ┆   ┆ ce          ┆ ice         ┆ ce         ┆ ice        │
│ i64 ┆ str         ┆ str  ┆ ---         ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│     ┆             ┆      ┆ i64         ┆   ┆ f64         ┆ f64         ┆ f64        ┆ f64        │
╞═════╪═════════════╪══════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 0   ┆ 2026-03-28  ┆ ETH  ┆ 15          ┆ … ┆ 0.47        ┆ 0.48        ┆ 0.52       ┆ 0.53       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 1   ┆ 2026-03-28  ┆ XRP  ┆ 15          ┆ … ┆ 0.45        ┆ 0.46        ┆ 0.54       ┆ 0.55       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 2   ┆ 2026-03-28  ┆ SOL  ┆ 15          ┆ … ┆ 0.49        ┆ 0.5         ┆ 0.5        ┆ 0.51       │
│     ┆ 18:00:42.72 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5060+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 3   ┆ 2026-03-28  ┆ BTC  ┆ 15          ┆ … ┆ 0.54        ┆ 0.55        ┆ 0.45       ┆ 0.46       │
│     ┆ 18:00:43.73 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5854+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│ 4   ┆ 2026-03-28  ┆ ETH  ┆ 15          ┆ … ┆ 0.47        ┆ 0.48        ┆ 0.52       ┆ 0.53       │
│     ┆ 18:00:43.73 ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
│     ┆ 5854+00:…   ┆      ┆             ┆   ┆             ┆             ┆            ┆            │
└─────┴─────────────┴──────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘