In [1]:
import numpy as np 
import polars as pl

In [34]:
df = pl.scan_csv(r'/Users/erxcshi/courses/ml1grad/crypto_pred_market/data_gather/final_data/final_data.csv').collect()

In [35]:
df.head()

shape: (5, 54)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ curr_time ┆ open_time ┆ close_tim ┆ prev_time ┆ … ┆ btc_spot_ ┆ btc_spot_ ┆ btc_spot_ ┆ btc_spot │
│ ---       ┆ ---       ┆ e         ┆ ---       ┆   ┆ return_vo ┆ return_vo ┆ signed_fl ┆ _size_me │
│ str       ┆ str       ┆ ---       ┆ str       ┆   ┆ l_30s     ┆ l_5m      ┆ ow_mean_3 ┆ an_30s   │
│           ┆           ┆ str       ┆           ┆   ┆ ---       ┆ ---       ┆ 0s        ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆ ---       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1T10:47:3 ┆ 1T10:45:0 ┆ 1T11:00:0 ┆ 1T10:47:3 ┆   ┆           ┆           ┆           ┆          │
│ 3.863137+ ┆ 0.000000+ ┆ 0.000000+ ┆ 2.862397+ ┆   ┆           ┆           ┆           ┆          │
│ 000…      ┆ 000…      ┆ 000…      ┆ 000…      ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1T10:47:3 ┆ 1T10:45:0 ┆ 1T11:00:0 ┆ 1T10:47:3 ┆   ┆           ┆           ┆           ┆          │
│ 4.863913+ ┆ 0.000000+ ┆ 0.000000+ ┆ 3.863137+ ┆   ┆           ┆           ┆           ┆          │
│ 000…      ┆ 000…      ┆ 000…      ┆ 000…      ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1T10:47:3 ┆ 1T10:45:0 ┆ 1T11:00:0 ┆ 1T10:47:3 ┆   ┆           ┆           ┆           ┆          │
│ 5.864626+ ┆ 0.000000+ ┆ 0.000000+ ┆ 4.863913+ ┆   ┆           ┆           ┆           ┆          │
│ 000…      ┆ 000…      ┆ 000…      ┆ 000…      ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1T10:47:3 ┆ 1T10:45:0 ┆ 1T11:00:0 ┆ 1T10:47:3 ┆   ┆           ┆           ┆           ┆          │
│ 6.866221+ ┆ 0.000000+ ┆ 0.000000+ ┆ 5.864626+ ┆   ┆           ┆           ┆           ┆          │
│ 000…      ┆ 000…      ┆ 000…      ┆ 000…      ┆   ┆           ┆           ┆           ┆          │
│ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ 2026-03-2 ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 1T10:47:3 ┆ 1T10:45:0 ┆ 1T11:00:0 ┆ 1T10:47:3 ┆   ┆           ┆           ┆           ┆          │
│ 7.866620+ ┆ 0.000000+ ┆ 0.000000+ ┆ 6.866221+ ┆   ┆           ┆           ┆           ┆          │
│ 000…      ┆ 000…      ┆ 000…      ┆ 000…      ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
def _to_datetime(table: pl.DataFrame, cols: list) -> pl.DataFrame:
        for col in cols: 
            table = table.with_columns(
                pl.col(col)
                .str.to_datetime(format="%Y-%m-%dT%H:%M:%S%.f%#z", strict=False)
                .alias(col)
            )
        return table

df = _to_datetime(df, cols = ['curr_time', 'open_time', 'close_time', 'prev_time'])

In [ ]:
event_col_ids = ['open_time', 'close_time']
event_ids = (df.select(event_col_ids).unique().sort('open_time'))
n = 0.7

train_event_ids = event_ids[:round(n*len(event_ids))]
test_event_ids = event_ids[round(n*len(event_ids)):]

In [ ]:
train_df = df.join(train_event_ids, on = event_col_ids)

shape: (1_184, 2)
┌─────────────────────────┬─────────────────────────┐
│ open_time               ┆ close_time              │
│ ---                     ┆ ---                     │
│ datetime[μs, UTC]       ┆ datetime[μs, UTC]       │
╞═════════════════════════╪═════════════════════════╡
│ 2026-03-26 13:00:00 UTC ┆ 2026-03-26 13:15:00 UTC │
│ 2026-03-22 16:00:00 UTC ┆ 2026-03-22 16:15:00 UTC │
│ 2026-03-31 04:30:00 UTC ┆ 2026-03-31 04:45:00 UTC │
│ 2026-04-02 00:45:00 UTC ┆ 2026-04-02 01:00:00 UTC │
│ 2026-03-27 00:00:00 UTC ┆ 2026-03-27 00:15:00 UTC │
│ …                       ┆ …                       │
│ 2026-04-01 23:45:00 UTC ┆ 2026-04-02 00:00:00 UTC │
│ 2026-03-26 05:15:00 UTC ┆ 2026-03-26 05:30:00 UTC │
│ 2026-04-01 13:15:00 UTC ┆ 2026-04-01 13:30:00 UTC │
│ 2026-03-29 11:45:00 UTC ┆ 2026-03-29 12:00:00 UTC │
│ 2026-03-24 19:00:00 UTC ┆ 2026-03-24 19:15:00 UTC │
└─────────────────────────┴─────────────────────────┘

In [ ]:
X_train